apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb

---

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mongo-root-username:  dXNlcm5hbWU=
  mongo-root-password:  cGFzc3dvcmQ=

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: tcp
      protocol: TCP
      port: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongodb
spec:
 selector:
   matchLabels:
     app: mongodb
 serviceName: mongodb
 replicas: 1
 template:
   metadata:
     labels:
       app: mongodb
   spec:
     terminationGracePeriodSeconds: 10
     containers:
     - name: mongodb
       image: mongo:4.0
       ports:
       - containerPort: 27017
         name: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password