apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app1
  namespace: my-apps
  labels:
    app: my-web-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app1
  template:
    metadata:
      labels:
        app: my-web-app1
    spec:
      containers:
      - name: go-app-container
        image: mpratigyan/go-web-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  labels:
  name: my-web1-service
  namespace: my-apps
spec:
  selector:
    app: my-web-app1       
  ports:
    -protocol: TCP
     port: 3000
     targetPort: 3000
