apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: my-web-app1
  name: my-web-app1
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: my-web-app1
  template:
    metadata:
      labels:
        k8s-app: my-web-app1
    spec:
      containers:
      - name: my-web-app1
        image: mpratigyan/go-web-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: my-web-app1
  name: my-web-app1
  namespace: my-apps
spec:
  selector:
    k8s-app: my-web-app1       
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
