apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app2
  namespace: my-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app2
  template:
    metadata:
      labels:
        app: my-web-app2
    spec:
      containers:
      - name: go-app-container
        image: mpratigyan/go-web-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3333

----
kind: Service
apiVersion: v1
metadata:
  labels:
  name: my-web2-service
  namespace: my-apps
spec:
  selector:
    app: my-web-app2       
  ports:
    -protocol: TCP
     port: 3333
     targetPort: 3333
